import type { Parent } from "./types";

export const mockParents: Parent[] = [
  {
    id: "PAR001",
    name: "Rahul Sharma",
    fatherName: "Mahesh Sharma",
    motherName: "Sunita Sharma",
    email: "rahul@example.com",
    phone: "+91 9876543210",
    alternatePhone: "+91 9876543222",
    occupation: "Software Engineer",
    address: "Salt Lake Sector V",
    city: "Kolkata",
    state: "West Bengal",
    pinCode: "700091",
    photo: "https://i.pravatar.cc/150?img=11",
    status: "Active",
    students: [
      {
        id: "STD001",
        name: "Aarav Sharma",
        photo: "https://i.pravatar.cc/150?img=15",
        className: "Class 8",
        admissionNo: "ADM001",
        rollNumber: "12",
        attendance: 95,
        feeStatus: "Paid",
      },
      {
        id: "STD002",
        name: "Anaya Sharma",
        photo: "https://i.pravatar.cc/150?img=16",
        className: "Class 5",
        admissionNo: "ADM002",
        rollNumber: "08",
        attendance: 91,
        feeStatus: "Pending",
      },
    ],
  },
  {
    id: "PAR002",
    name: "Priya Das",
    fatherName: "N/A",
    motherName: "N/A",
    email: "priya@example.com",
    phone: "+91 9876541111",
    alternatePhone: "+91 9876541112",
    occupation: "Doctor",
    address: "New Town",
    city: "Kolkata",
    state: "West Bengal",
    pinCode: "700156",
    photo: "https://i.pravatar.cc/150?img=22",
    status: "Inactive",
    students: [
      {
        id: "STD003",
        name: "Riya Das",
        photo: "https://i.pravatar.cc/150?img=33",
        className: "Class 10",
        admissionNo: "ADM003",
        rollNumber: "05",
        attendance: 89,
        feeStatus: "Paid",
      },
    ],
  },
];