/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageNotFoundRouteImport } from './routes/page-not-found'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedTimetableRouteImport } from './routes/_protected/timetable'
import { Route as ProtectedTeachersRouteImport } from './routes/_protected/teachers'
import { Route as ProtectedStudentsRouteImport } from './routes/_protected/students'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedNewAnnouncementpageRouteImport } from './routes/_protected/new-announcementpage'
import { Route as ProtectedGradesRouteImport } from './routes/_protected/grades'
import { Route as ProtectedFeesRouteImport } from './routes/_protected/fees'
import { Route as ProtectedExamsRouteImport } from './routes/_protected/exams'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedClassesRouteImport } from './routes/_protected/classes'
import { Route as ProtectedAttendanceRouteImport } from './routes/_protected/attendance'
import { Route as ProtectedAnnouncementsRouteImport } from './routes/_protected/announcements'
import { Route as ProtectedAddExamsRouteImport } from './routes/_protected/add-exams'
import { Route as ProtectedNewInvoicePageRouteImport } from './routes/_protected/NewInvoicePage'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestContactRouteImport } from './routes/_guest/contact'
import { Route as GuestAboutUsRouteImport } from './routes/_guest/about-us'
import { Route as ProtectedParentsIndexRouteImport } from './routes/_protected/parents/index'
import { Route as ProtectedParentsAddParentRouteImport } from './routes/_protected/parents/add-parent'
import { Route as ProtectedParentsParentIdIndexRouteImport } from './routes/_protected/parents/$parentId/index'
import { Route as ProtectedParentsParentIdEditRouteImport } from './routes/_protected/parents/$parentId/edit'

const PageNotFoundRoute = PageNotFoundRouteImport.update({
  id: '/page-not-found',
  path: '/page-not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTimetableRoute = ProtectedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTeachersRoute = ProtectedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStudentsRoute = ProtectedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNewAnnouncementpageRoute =
  ProtectedNewAnnouncementpageRouteImport.update({
    id: '/new-announcementpage',
    path: '/new-announcementpage',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedGradesRoute = ProtectedGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFeesRoute = ProtectedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExamsRoute = ProtectedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedClassesRoute = ProtectedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAttendanceRoute = ProtectedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnnouncementsRoute = ProtectedAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAddExamsRoute = ProtectedAddExamsRouteImport.update({
  id: '/add-exams',
  path: '/add-exams',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNewInvoicePageRoute = ProtectedNewInvoicePageRouteImport.update({
  id: '/NewInvoicePage',
  path: '/NewInvoicePage',
  getParentRoute: () => ProtectedRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestContactRoute = GuestContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAboutUsRoute = GuestAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => GuestRoute,
} as any)
const ProtectedParentsIndexRoute = ProtectedParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedParentsAddParentRoute =
  ProtectedParentsAddParentRouteImport.update({
    id: '/parents/add-parent',
    path: '/parents/add-parent',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedParentsParentIdIndexRoute =
  ProtectedParentsParentIdIndexRouteImport.update({
    id: '/parents/$parentId/',
    path: '/parents/$parentId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedParentsParentIdEditRoute =
  ProtectedParentsParentIdEditRouteImport.update({
    id: '/parents/$parentId/edit',
    path: '/parents/$parentId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page-not-found': typeof PageNotFoundRoute
  '/about-us': typeof GuestAboutUsRoute
  '/contact': typeof GuestContactRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/NewInvoicePage': typeof ProtectedNewInvoicePageRoute
  '/add-exams': typeof ProtectedAddExamsRoute
  '/announcements': typeof ProtectedAnnouncementsRoute
  '/attendance': typeof ProtectedAttendanceRoute
  '/classes': typeof ProtectedClassesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/exams': typeof ProtectedExamsRoute
  '/fees': typeof ProtectedFeesRoute
  '/grades': typeof ProtectedGradesRoute
  '/new-announcementpage': typeof ProtectedNewAnnouncementpageRoute
  '/profile': typeof ProtectedProfileRoute
  '/students': typeof ProtectedStudentsRoute
  '/teachers': typeof ProtectedTeachersRoute
  '/timetable': typeof ProtectedTimetableRoute
  '/parents/add-parent': typeof ProtectedParentsAddParentRoute
  '/parents/': typeof ProtectedParentsIndexRoute
  '/parents/$parentId/edit': typeof ProtectedParentsParentIdEditRoute
  '/parents/$parentId/': typeof ProtectedParentsParentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page-not-found': typeof PageNotFoundRoute
  '/about-us': typeof GuestAboutUsRoute
  '/contact': typeof GuestContactRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/NewInvoicePage': typeof ProtectedNewInvoicePageRoute
  '/add-exams': typeof ProtectedAddExamsRoute
  '/announcements': typeof ProtectedAnnouncementsRoute
  '/attendance': typeof ProtectedAttendanceRoute
  '/classes': typeof ProtectedClassesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/exams': typeof ProtectedExamsRoute
  '/fees': typeof ProtectedFeesRoute
  '/grades': typeof ProtectedGradesRoute
  '/new-announcementpage': typeof ProtectedNewAnnouncementpageRoute
  '/profile': typeof ProtectedProfileRoute
  '/students': typeof ProtectedStudentsRoute
  '/teachers': typeof ProtectedTeachersRoute
  '/timetable': typeof ProtectedTimetableRoute
  '/parents/add-parent': typeof ProtectedParentsAddParentRoute
  '/parents': typeof ProtectedParentsIndexRoute
  '/parents/$parentId/edit': typeof ProtectedParentsParentIdEditRoute
  '/parents/$parentId': typeof ProtectedParentsParentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_guest': typeof GuestRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/page-not-found': typeof PageNotFoundRoute
  '/_guest/about-us': typeof GuestAboutUsRoute
  '/_guest/contact': typeof GuestContactRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_protected/NewInvoicePage': typeof ProtectedNewInvoicePageRoute
  '/_protected/add-exams': typeof ProtectedAddExamsRoute
  '/_protected/announcements': typeof ProtectedAnnouncementsRoute
  '/_protected/attendance': typeof ProtectedAttendanceRoute
  '/_protected/classes': typeof ProtectedClassesRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/exams': typeof ProtectedExamsRoute
  '/_protected/fees': typeof ProtectedFeesRoute
  '/_protected/grades': typeof ProtectedGradesRoute
  '/_protected/new-announcementpage': typeof ProtectedNewAnnouncementpageRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/students': typeof ProtectedStudentsRoute
  '/_protected/teachers': typeof ProtectedTeachersRoute
  '/_protected/timetable': typeof ProtectedTimetableRoute
  '/_protected/parents/add-parent': typeof ProtectedParentsAddParentRoute
  '/_protected/parents/': typeof ProtectedParentsIndexRoute
  '/_protected/parents/$parentId/edit': typeof ProtectedParentsParentIdEditRoute
  '/_protected/parents/$parentId/': typeof ProtectedParentsParentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/page-not-found'
    | '/about-us'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/NewInvoicePage'
    | '/add-exams'
    | '/announcements'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/exams'
    | '/fees'
    | '/grades'
    | '/new-announcementpage'
    | '/profile'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/parents/add-parent'
    | '/parents/'
    | '/parents/$parentId/edit'
    | '/parents/$parentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/page-not-found'
    | '/about-us'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/NewInvoicePage'
    | '/add-exams'
    | '/announcements'
    | '/attendance'
    | '/classes'
    | '/dashboard'
    | '/exams'
    | '/fees'
    | '/grades'
    | '/new-announcementpage'
    | '/profile'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/parents/add-parent'
    | '/parents'
    | '/parents/$parentId/edit'
    | '/parents/$parentId'
  id:
    | '__root__'
    | '/'
    | '/_guest'
    | '/_protected'
    | '/page-not-found'
    | '/_guest/about-us'
    | '/_guest/contact'
    | '/_guest/forgot-password'
    | '/_guest/login'
    | '/_guest/register'
    | '/_protected/NewInvoicePage'
    | '/_protected/add-exams'
    | '/_protected/announcements'
    | '/_protected/attendance'
    | '/_protected/classes'
    | '/_protected/dashboard'
    | '/_protected/exams'
    | '/_protected/fees'
    | '/_protected/grades'
    | '/_protected/new-announcementpage'
    | '/_protected/profile'
    | '/_protected/students'
    | '/_protected/teachers'
    | '/_protected/timetable'
    | '/_protected/parents/add-parent'
    | '/_protected/parents/'
    | '/_protected/parents/$parentId/edit'
    | '/_protected/parents/$parentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRoute: typeof GuestRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PageNotFoundRoute: typeof PageNotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page-not-found': {
      id: '/page-not-found'
      path: '/page-not-found'
      fullPath: '/page-not-found'
      preLoaderRoute: typeof PageNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/timetable': {
      id: '/_protected/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof ProtectedTimetableRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teachers': {
      id: '/_protected/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof ProtectedTeachersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/students': {
      id: '/_protected/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof ProtectedStudentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/new-announcementpage': {
      id: '/_protected/new-announcementpage'
      path: '/new-announcementpage'
      fullPath: '/new-announcementpage'
      preLoaderRoute: typeof ProtectedNewAnnouncementpageRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/grades': {
      id: '/_protected/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof ProtectedGradesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/fees': {
      id: '/_protected/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof ProtectedFeesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/exams': {
      id: '/_protected/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ProtectedExamsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classes': {
      id: '/_protected/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ProtectedClassesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/attendance': {
      id: '/_protected/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof ProtectedAttendanceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/announcements': {
      id: '/_protected/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof ProtectedAnnouncementsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/add-exams': {
      id: '/_protected/add-exams'
      path: '/add-exams'
      fullPath: '/add-exams'
      preLoaderRoute: typeof ProtectedAddExamsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/NewInvoicePage': {
      id: '/_protected/NewInvoicePage'
      path: '/NewInvoicePage'
      fullPath: '/NewInvoicePage'
      preLoaderRoute: typeof ProtectedNewInvoicePageRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/contact': {
      id: '/_guest/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof GuestContactRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/about-us': {
      id: '/_guest/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof GuestAboutUsRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_protected/parents/': {
      id: '/_protected/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof ProtectedParentsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/parents/add-parent': {
      id: '/_protected/parents/add-parent'
      path: '/parents/add-parent'
      fullPath: '/parents/add-parent'
      preLoaderRoute: typeof ProtectedParentsAddParentRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/parents/$parentId/': {
      id: '/_protected/parents/$parentId/'
      path: '/parents/$parentId'
      fullPath: '/parents/$parentId/'
      preLoaderRoute: typeof ProtectedParentsParentIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/parents/$parentId/edit': {
      id: '/_protected/parents/$parentId/edit'
      path: '/parents/$parentId/edit'
      fullPath: '/parents/$parentId/edit'
      preLoaderRoute: typeof ProtectedParentsParentIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface GuestRouteChildren {
  GuestAboutUsRoute: typeof GuestAboutUsRoute
  GuestContactRoute: typeof GuestContactRoute
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestAboutUsRoute: GuestAboutUsRoute,
  GuestContactRoute: GuestContactRoute,
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface ProtectedRouteChildren {
  ProtectedNewInvoicePageRoute: typeof ProtectedNewInvoicePageRoute
  ProtectedAddExamsRoute: typeof ProtectedAddExamsRoute
  ProtectedAnnouncementsRoute: typeof ProtectedAnnouncementsRoute
  ProtectedAttendanceRoute: typeof ProtectedAttendanceRoute
  ProtectedClassesRoute: typeof ProtectedClassesRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedExamsRoute: typeof ProtectedExamsRoute
  ProtectedFeesRoute: typeof ProtectedFeesRoute
  ProtectedGradesRoute: typeof ProtectedGradesRoute
  ProtectedNewAnnouncementpageRoute: typeof ProtectedNewAnnouncementpageRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedStudentsRoute: typeof ProtectedStudentsRoute
  ProtectedTeachersRoute: typeof ProtectedTeachersRoute
  ProtectedTimetableRoute: typeof ProtectedTimetableRoute
  ProtectedParentsAddParentRoute: typeof ProtectedParentsAddParentRoute
  ProtectedParentsIndexRoute: typeof ProtectedParentsIndexRoute
  ProtectedParentsParentIdEditRoute: typeof ProtectedParentsParentIdEditRoute
  ProtectedParentsParentIdIndexRoute: typeof ProtectedParentsParentIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedNewInvoicePageRoute: ProtectedNewInvoicePageRoute,
  ProtectedAddExamsRoute: ProtectedAddExamsRoute,
  ProtectedAnnouncementsRoute: ProtectedAnnouncementsRoute,
  ProtectedAttendanceRoute: ProtectedAttendanceRoute,
  ProtectedClassesRoute: ProtectedClassesRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedExamsRoute: ProtectedExamsRoute,
  ProtectedFeesRoute: ProtectedFeesRoute,
  ProtectedGradesRoute: ProtectedGradesRoute,
  ProtectedNewAnnouncementpageRoute: ProtectedNewAnnouncementpageRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedStudentsRoute: ProtectedStudentsRoute,
  ProtectedTeachersRoute: ProtectedTeachersRoute,
  ProtectedTimetableRoute: ProtectedTimetableRoute,
  ProtectedParentsAddParentRoute: ProtectedParentsAddParentRoute,
  ProtectedParentsIndexRoute: ProtectedParentsIndexRoute,
  ProtectedParentsParentIdEditRoute: ProtectedParentsParentIdEditRoute,
  ProtectedParentsParentIdIndexRoute: ProtectedParentsParentIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRoute: GuestRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PageNotFoundRoute: PageNotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
